### ISSUE TITLE
Exception when networks list is empty. Some users or service account may not have permissions to list networks or the project doesn't have any networks

### ISSUE THREAD

**Issue by DanElias** [GoogleCloudDataproc/dataproc-jupyter-plugin#152]
https://github.com/GoogleCloudDataproc/dataproc-jupyter-plugin/blame/e06b9fdd41bc9819d7c23d9505ef079479789003/src/runtime/runtimeService.tsx#L481

Some users or service account may not have permissions to list networks or the project doesn't have any networks

As the code is trying to access [0] this throws the exception "Error listing Networks" as the networks array is empty

The exception is not specific - it could be raised by either the HTTP Request failing or the networks list being empty, could we please add a check before line https://github.com/GoogleCloudDataproc/dataproc-jupyter-plugin/blame/e06b9fdd41bc9819d7c23d9505ef079479789003/src/runtime/runtimeService.tsx#L481

such as: 

```
setNetworklist(transformedNetworkList);
if (selectedRuntimeClone === undefined) {
  if (transformedNetworkList.length > 0) {
    setNetworkSelected(transformedNetworkList[0]);
  } else {
    DataprocLoggingService.log('No networks found. Account may lack access to list networks', LOG_LEVEL.ERROR);
    toast.error(`No networks found. Account may lack access to list networks.`, toastifyCustomStyle);
  }
}
```

**Comment by DanElias** [comment]
We cannot assume the list will always have 1 network. Some users don't even have a default network in their project due to org policies.

**Comment by DanElias** [comment]
Tried to create a commit but I don't have permission to push to my branch in the repository.

**Comment by ywskycn** [comment]
Thanks for catching this @DanElias . Are you able to folk the repo, commit your changes in your own branch/repo, and create a PR here?

**Comment by DanElias** [comment]
Hi @ywskycn added PR: https://github.com/GoogleCloudDataproc/dataproc-jupyter-plugin/pull/153

Just wondering, do you have tests in place to check my changes don't break anything? Thanks!

**Comment by ojarjur** [comment]
> Hi @ywskycn added PR: #153
> 
> Just wondering, do you have tests in place to check my changes don't break anything? Thanks!

We have manual tests that are slowly being automated using playwright, but the tests for this particular UI are still manual.

**Comment by DanElias** [comment]
Merged into main
